version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  sage:
    build:
      context: ./
      dockerfile: ./sage/Dockerfile
